package com.management_system.dao;

import com.management_system.model.GoodsInf;

public interface GoodsInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_inf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_inf
     *
     * @mbggenerated
     */
    int insert(GoodsInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_inf
     *
     * @mbggenerated
     */
    int insertSelective(GoodsInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_inf
     *
     * @mbggenerated
     */
    GoodsInf selectByPrimaryKey(String goodsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_inf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GoodsInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_inf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GoodsInf record);
}