package com.management_system.dao;

import com.management_system.model.ImportOrder;

import java.util.List;

public interface ImportOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_order
     *
     * @mbggenerated
     */
    int insert(ImportOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_order
     *
     * @mbggenerated
     */
    int insertSelective(ImportOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_order
     *
     * @mbggenerated
     */
    ImportOrder selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImportOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImportOrder record);

    List<ImportOrder> selectAll();
}