package com.management_system.dao;

import com.management_system.model.Manufacturer;

public interface ManufacturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturer
     *
     * @mbggenerated
     */
    int insert(Manufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturer
     *
     * @mbggenerated
     */
    int insertSelective(Manufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturer
     *
     * @mbggenerated
     */
    Manufacturer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Manufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table manufacturer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Manufacturer record);

    int getManufacturerId(String name);
}