package com.management_system.model;

public class Agent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.ygid
     *
     * @mbggenerated
     */
    private String ygid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.ygmc
     *
     * @mbggenerated
     */
    private String ygmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.xsje
     *
     * @mbggenerated
     */
    private String xsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.thje
     *
     * @mbggenerated
     */
    private String thje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.shje
     *
     * @mbggenerated
     */
    private String shje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.wsje
     *
     * @mbggenerated
     */
    private String wsje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agent.czy
     *
     * @mbggenerated
     */
    private String czy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.id
     *
     * @return the value of agent.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.id
     *
     * @param id the value for agent.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.ygid
     *
     * @return the value of agent.ygid
     *
     * @mbggenerated
     */
    public String getYgid() {
        return ygid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.ygid
     *
     * @param ygid the value for agent.ygid
     *
     * @mbggenerated
     */
    public void setYgid(String ygid) {
        this.ygid = ygid == null ? null : ygid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.ygmc
     *
     * @return the value of agent.ygmc
     *
     * @mbggenerated
     */
    public String getYgmc() {
        return ygmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.ygmc
     *
     * @param ygmc the value for agent.ygmc
     *
     * @mbggenerated
     */
    public void setYgmc(String ygmc) {
        this.ygmc = ygmc == null ? null : ygmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.xsje
     *
     * @return the value of agent.xsje
     *
     * @mbggenerated
     */
    public String getXsje() {
        return xsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.xsje
     *
     * @param xsje the value for agent.xsje
     *
     * @mbggenerated
     */
    public void setXsje(String xsje) {
        this.xsje = xsje == null ? null : xsje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.thje
     *
     * @return the value of agent.thje
     *
     * @mbggenerated
     */
    public String getThje() {
        return thje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.thje
     *
     * @param thje the value for agent.thje
     *
     * @mbggenerated
     */
    public void setThje(String thje) {
        this.thje = thje == null ? null : thje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.shje
     *
     * @return the value of agent.shje
     *
     * @mbggenerated
     */
    public String getShje() {
        return shje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.shje
     *
     * @param shje the value for agent.shje
     *
     * @mbggenerated
     */
    public void setShje(String shje) {
        this.shje = shje == null ? null : shje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.wsje
     *
     * @return the value of agent.wsje
     *
     * @mbggenerated
     */
    public String getWsje() {
        return wsje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.wsje
     *
     * @param wsje the value for agent.wsje
     *
     * @mbggenerated
     */
    public void setWsje(String wsje) {
        this.wsje = wsje == null ? null : wsje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column agent.czy
     *
     * @return the value of agent.czy
     *
     * @mbggenerated
     */
    public String getCzy() {
        return czy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column agent.czy
     *
     * @param czy the value for agent.czy
     *
     * @mbggenerated
     */
    public void setCzy(String czy) {
        this.czy = czy == null ? null : czy.trim();
    }
}