package com.management_system.model;

public class Ck {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ck.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ck.ckmc
     *
     * @mbggenerated
     */
    private String ckmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ck.jm
     *
     * @mbggenerated
     */
    private String jm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ck.fzr
     *
     * @mbggenerated
     */
    private String fzr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ck.lxdh
     *
     * @mbggenerated
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ck.dz
     *
     * @mbggenerated
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ck.bz
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ck.mrck
     *
     * @mbggenerated
     */
    private String mrck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ck.pjck
     *
     * @mbggenerated
     */
    private String pjck;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ck.id
     *
     * @return the value of ck.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ck.id
     *
     * @param id the value for ck.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ck.ckmc
     *
     * @return the value of ck.ckmc
     *
     * @mbggenerated
     */
    public String getCkmc() {
        return ckmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ck.ckmc
     *
     * @param ckmc the value for ck.ckmc
     *
     * @mbggenerated
     */
    public void setCkmc(String ckmc) {
        this.ckmc = ckmc == null ? null : ckmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ck.jm
     *
     * @return the value of ck.jm
     *
     * @mbggenerated
     */
    public String getJm() {
        return jm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ck.jm
     *
     * @param jm the value for ck.jm
     *
     * @mbggenerated
     */
    public void setJm(String jm) {
        this.jm = jm == null ? null : jm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ck.fzr
     *
     * @return the value of ck.fzr
     *
     * @mbggenerated
     */
    public String getFzr() {
        return fzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ck.fzr
     *
     * @param fzr the value for ck.fzr
     *
     * @mbggenerated
     */
    public void setFzr(String fzr) {
        this.fzr = fzr == null ? null : fzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ck.lxdh
     *
     * @return the value of ck.lxdh
     *
     * @mbggenerated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ck.lxdh
     *
     * @param lxdh the value for ck.lxdh
     *
     * @mbggenerated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ck.dz
     *
     * @return the value of ck.dz
     *
     * @mbggenerated
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ck.dz
     *
     * @param dz the value for ck.dz
     *
     * @mbggenerated
     */
    public void setDz(String dz) {
        this.dz = dz == null ? null : dz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ck.bz
     *
     * @return the value of ck.bz
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ck.bz
     *
     * @param bz the value for ck.bz
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ck.mrck
     *
     * @return the value of ck.mrck
     *
     * @mbggenerated
     */
    public String getMrck() {
        return mrck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ck.mrck
     *
     * @param mrck the value for ck.mrck
     *
     * @mbggenerated
     */
    public void setMrck(String mrck) {
        this.mrck = mrck == null ? null : mrck.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ck.pjck
     *
     * @return the value of ck.pjck
     *
     * @mbggenerated
     */
    public String getPjck() {
        return pjck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ck.pjck
     *
     * @param pjck the value for ck.pjck
     *
     * @mbggenerated
     */
    public void setPjck(String pjck) {
        this.pjck = pjck == null ? null : pjck.trim();
    }
}