package com.management_system.model;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer
     *
     * @mbggenerated
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.jm
     *
     * @mbggenerated
     */
    private String jm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.lxr
     *
     * @mbggenerated
     */
    private String lxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.lxdh
     *
     * @mbggenerated
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.lxdz
     *
     * @mbggenerated
     */
    private String lxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.bz
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.lwje
     *
     * @mbggenerated
     */
    private String lwje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.mrkh
     *
     * @mbggenerated
     */
    private String mrkh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.pl
     *
     * @mbggenerated
     */
    private String pl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.lx
     *
     * @mbggenerated
     */
    private String lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.dq
     *
     * @mbggenerated
     */
    private String dq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.jy
     *
     * @mbggenerated
     */
    private String jy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer
     *
     * @return the value of customer.customer
     *
     * @mbggenerated
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer
     *
     * @param customer the value for customer.customer
     *
     * @mbggenerated
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.jm
     *
     * @return the value of customer.jm
     *
     * @mbggenerated
     */
    public String getJm() {
        return jm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.jm
     *
     * @param jm the value for customer.jm
     *
     * @mbggenerated
     */
    public void setJm(String jm) {
        this.jm = jm == null ? null : jm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.lxr
     *
     * @return the value of customer.lxr
     *
     * @mbggenerated
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.lxr
     *
     * @param lxr the value for customer.lxr
     *
     * @mbggenerated
     */
    public void setLxr(String lxr) {
        this.lxr = lxr == null ? null : lxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.lxdh
     *
     * @return the value of customer.lxdh
     *
     * @mbggenerated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.lxdh
     *
     * @param lxdh the value for customer.lxdh
     *
     * @mbggenerated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.lxdz
     *
     * @return the value of customer.lxdz
     *
     * @mbggenerated
     */
    public String getLxdz() {
        return lxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.lxdz
     *
     * @param lxdz the value for customer.lxdz
     *
     * @mbggenerated
     */
    public void setLxdz(String lxdz) {
        this.lxdz = lxdz == null ? null : lxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.bz
     *
     * @return the value of customer.bz
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.bz
     *
     * @param bz the value for customer.bz
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.lwje
     *
     * @return the value of customer.lwje
     *
     * @mbggenerated
     */
    public String getLwje() {
        return lwje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.lwje
     *
     * @param lwje the value for customer.lwje
     *
     * @mbggenerated
     */
    public void setLwje(String lwje) {
        this.lwje = lwje == null ? null : lwje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.mrkh
     *
     * @return the value of customer.mrkh
     *
     * @mbggenerated
     */
    public String getMrkh() {
        return mrkh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.mrkh
     *
     * @param mrkh the value for customer.mrkh
     *
     * @mbggenerated
     */
    public void setMrkh(String mrkh) {
        this.mrkh = mrkh == null ? null : mrkh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.pl
     *
     * @return the value of customer.pl
     *
     * @mbggenerated
     */
    public String getPl() {
        return pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.pl
     *
     * @param pl the value for customer.pl
     *
     * @mbggenerated
     */
    public void setPl(String pl) {
        this.pl = pl == null ? null : pl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.lx
     *
     * @return the value of customer.lx
     *
     * @mbggenerated
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.lx
     *
     * @param lx the value for customer.lx
     *
     * @mbggenerated
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.dq
     *
     * @return the value of customer.dq
     *
     * @mbggenerated
     */
    public String getDq() {
        return dq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.dq
     *
     * @param dq the value for customer.dq
     *
     * @mbggenerated
     */
    public void setDq(String dq) {
        this.dq = dq == null ? null : dq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.jy
     *
     * @return the value of customer.jy
     *
     * @mbggenerated
     */
    public String getJy() {
        return jy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.jy
     *
     * @param jy the value for customer.jy
     *
     * @mbggenerated
     */
    public void setJy(String jy) {
        this.jy = jy == null ? null : jy.trim();
    }
}