package com.management_system.model;

public class GoodsInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.goods_name
     *
     * @mbggenerated
     */
    private String goodsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.banned
     *
     * @mbggenerated
     */
    private String banned;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.goods_type
     *
     * @mbggenerated
     */
    private String goodsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.color
     *
     * @mbggenerated
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.goods_barcode
     *
     * @mbggenerated
     */
    private String goodsBarcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.min_inventory
     *
     * @mbggenerated
     */
    private String minInventory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.pre_in_price
     *
     * @mbggenerated
     */
    private Integer preInPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.pre_out_price
     *
     * @mbggenerated
     */
    private Integer preOutPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.sales commission
     *
     * @mbggenerated
     */
    private String salesCommission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.manufacturer
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_inf.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.goods_id
     *
     * @return the value of goods_inf.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.goods_id
     *
     * @param goodsId the value for goods_inf.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.goods_name
     *
     * @return the value of goods_inf.goods_name
     *
     * @mbggenerated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.goods_name
     *
     * @param goodsName the value for goods_inf.goods_name
     *
     * @mbggenerated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.code
     *
     * @return the value of goods_inf.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.code
     *
     * @param code the value for goods_inf.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.banned
     *
     * @return the value of goods_inf.banned
     *
     * @mbggenerated
     */
    public String getBanned() {
        return banned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.banned
     *
     * @param banned the value for goods_inf.banned
     *
     * @mbggenerated
     */
    public void setBanned(String banned) {
        this.banned = banned == null ? null : banned.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.goods_type
     *
     * @return the value of goods_inf.goods_type
     *
     * @mbggenerated
     */
    public String getGoodsType() {
        return goodsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.goods_type
     *
     * @param goodsType the value for goods_inf.goods_type
     *
     * @mbggenerated
     */
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType == null ? null : goodsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.unit
     *
     * @return the value of goods_inf.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.unit
     *
     * @param unit the value for goods_inf.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.type
     *
     * @return the value of goods_inf.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.type
     *
     * @param type the value for goods_inf.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.color
     *
     * @return the value of goods_inf.color
     *
     * @mbggenerated
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.color
     *
     * @param color the value for goods_inf.color
     *
     * @mbggenerated
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.goods_barcode
     *
     * @return the value of goods_inf.goods_barcode
     *
     * @mbggenerated
     */
    public String getGoodsBarcode() {
        return goodsBarcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.goods_barcode
     *
     * @param goodsBarcode the value for goods_inf.goods_barcode
     *
     * @mbggenerated
     */
    public void setGoodsBarcode(String goodsBarcode) {
        this.goodsBarcode = goodsBarcode == null ? null : goodsBarcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.min_inventory
     *
     * @return the value of goods_inf.min_inventory
     *
     * @mbggenerated
     */
    public String getMinInventory() {
        return minInventory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.min_inventory
     *
     * @param minInventory the value for goods_inf.min_inventory
     *
     * @mbggenerated
     */
    public void setMinInventory(String minInventory) {
        this.minInventory = minInventory == null ? null : minInventory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.pre_in_price
     *
     * @return the value of goods_inf.pre_in_price
     *
     * @mbggenerated
     */
    public Integer getPreInPrice() {
        return preInPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.pre_in_price
     *
     * @param preInPrice the value for goods_inf.pre_in_price
     *
     * @mbggenerated
     */
    public void setPreInPrice(Integer preInPrice) {
        this.preInPrice = preInPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.pre_out_price
     *
     * @return the value of goods_inf.pre_out_price
     *
     * @mbggenerated
     */
    public Integer getPreOutPrice() {
        return preOutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.pre_out_price
     *
     * @param preOutPrice the value for goods_inf.pre_out_price
     *
     * @mbggenerated
     */
    public void setPreOutPrice(Integer preOutPrice) {
        this.preOutPrice = preOutPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.sales commission
     *
     * @return the value of goods_inf.sales commission
     *
     * @mbggenerated
     */
    public String getSalesCommission() {
        return salesCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.sales commission
     *
     * @param salesCommission the value for goods_inf.sales commission
     *
     * @mbggenerated
     */
    public void setSalesCommission(String salesCommission) {
        this.salesCommission = salesCommission == null ? null : salesCommission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.manufacturer
     *
     * @return the value of goods_inf.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.manufacturer
     *
     * @param manufacturer the value for goods_inf.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_inf.remarks
     *
     * @return the value of goods_inf.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_inf.remarks
     *
     * @param remarks the value for goods_inf.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}