package com.management_system.model;

import java.util.Date;

public class ImportOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.manufacturer
     *
     * @mbggenerated
     */
    private Integer manufacturer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.ck
     *
     * @mbggenerated
     */
    private Integer ck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.yfje
     *
     * @mbggenerated
     */
    private Integer yfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.sfje
     *
     * @mbggenerated
     */
    private Integer sfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.agent
     *
     * @mbggenerated
     */
    private String agent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.bz
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.czy
     *
     * @mbggenerated
     */
    private String czy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.bid
     *
     * @mbggenerated
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.yhje
     *
     * @mbggenerated
     */
    private Integer yhje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.num
     *
     * @mbggenerated
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column import_order.th
     *
     * @mbggenerated
     */
    private String th;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.id
     *
     * @return the value of import_order.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.id
     *
     * @param id the value for import_order.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.manufacturer
     *
     * @return the value of import_order.manufacturer
     *
     * @mbggenerated
     */
    public Integer getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.manufacturer
     *
     * @param manufacturer the value for import_order.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(Integer manufacturer) {
        this.manufacturer = manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.ck
     *
     * @return the value of import_order.ck
     *
     * @mbggenerated
     */
    public Integer getCk() {
        return ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.ck
     *
     * @param ck the value for import_order.ck
     *
     * @mbggenerated
     */
    public void setCk(Integer ck) {
        this.ck = ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.date
     *
     * @return the value of import_order.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.date
     *
     * @param date the value for import_order.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.yfje
     *
     * @return the value of import_order.yfje
     *
     * @mbggenerated
     */
    public Integer getYfje() {
        return yfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.yfje
     *
     * @param yfje the value for import_order.yfje
     *
     * @mbggenerated
     */
    public void setYfje(Integer yfje) {
        this.yfje = yfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.sfje
     *
     * @return the value of import_order.sfje
     *
     * @mbggenerated
     */
    public Integer getSfje() {
        return sfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.sfje
     *
     * @param sfje the value for import_order.sfje
     *
     * @mbggenerated
     */
    public void setSfje(Integer sfje) {
        this.sfje = sfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.agent
     *
     * @return the value of import_order.agent
     *
     * @mbggenerated
     */
    public int getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.agent
     *
     * @param agent the value for import_order.agent
     *
     * @mbggenerated
     */
    public void setAgent(String agent) {
        this.agent = agent == null ? null : agent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.bz
     *
     * @return the value of import_order.bz
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.bz
     *
     * @param bz the value for import_order.bz
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.czy
     *
     * @return the value of import_order.czy
     *
     * @mbggenerated
     */
    public String getCzy() {
        return czy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.czy
     *
     * @param czy the value for import_order.czy
     *
     * @mbggenerated
     */
    public void setCzy(String czy) {
        this.czy = czy == null ? null : czy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.bid
     *
     * @return the value of import_order.bid
     *
     * @mbggenerated
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.bid
     *
     * @param bid the value for import_order.bid
     *
     * @mbggenerated
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.yhje
     *
     * @return the value of import_order.yhje
     *
     * @mbggenerated
     */
    public Integer getYhje() {
        return yhje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.yhje
     *
     * @param yhje the value for import_order.yhje
     *
     * @mbggenerated
     */
    public void setYhje(Integer yhje) {
        this.yhje = yhje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.num
     *
     * @return the value of import_order.num
     *
     * @mbggenerated
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.num
     *
     * @param num the value for import_order.num
     *
     * @mbggenerated
     */
    public void setNum(String num) {
        this.num = num == null ? null : num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column import_order.th
     *
     * @return the value of import_order.th
     *
     * @mbggenerated
     */
    public String getTh() {
        return th;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column import_order.th
     *
     * @param th the value for import_order.th
     *
     * @mbggenerated
     */
    public void setTh(String th) {
        this.th = th == null ? null : th.trim();
    }
}