package com.management_system.model;

public class Manufacturer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.ghsmc
     *
     * @mbggenerated
     */
    private String ghsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.jm
     *
     * @mbggenerated
     */
    private String jm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.lxr
     *
     * @mbggenerated
     */
    private String lxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.lxdh
     *
     * @mbggenerated
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.lxdz
     *
     * @mbggenerated
     */
    private String lxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.bz
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.lwje
     *
     * @mbggenerated
     */
    private String lwje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.mrghs
     *
     * @mbggenerated
     */
    private String mrghs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.pl
     *
     * @mbggenerated
     */
    private String pl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.lx
     *
     * @mbggenerated
     */
    private String lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.dq
     *
     * @mbggenerated
     */
    private String dq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column manufacturer.jy
     *
     * @mbggenerated
     */
    private String jy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.id
     *
     * @return the value of manufacturer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.id
     *
     * @param id the value for manufacturer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.ghsmc
     *
     * @return the value of manufacturer.ghsmc
     *
     * @mbggenerated
     */
    public String getGhsmc() {
        return ghsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.ghsmc
     *
     * @param ghsmc the value for manufacturer.ghsmc
     *
     * @mbggenerated
     */
    public void setGhsmc(String ghsmc) {
        this.ghsmc = ghsmc == null ? null : ghsmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.jm
     *
     * @return the value of manufacturer.jm
     *
     * @mbggenerated
     */
    public String getJm() {
        return jm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.jm
     *
     * @param jm the value for manufacturer.jm
     *
     * @mbggenerated
     */
    public void setJm(String jm) {
        this.jm = jm == null ? null : jm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.lxr
     *
     * @return the value of manufacturer.lxr
     *
     * @mbggenerated
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.lxr
     *
     * @param lxr the value for manufacturer.lxr
     *
     * @mbggenerated
     */
    public void setLxr(String lxr) {
        this.lxr = lxr == null ? null : lxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.lxdh
     *
     * @return the value of manufacturer.lxdh
     *
     * @mbggenerated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.lxdh
     *
     * @param lxdh the value for manufacturer.lxdh
     *
     * @mbggenerated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.lxdz
     *
     * @return the value of manufacturer.lxdz
     *
     * @mbggenerated
     */
    public String getLxdz() {
        return lxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.lxdz
     *
     * @param lxdz the value for manufacturer.lxdz
     *
     * @mbggenerated
     */
    public void setLxdz(String lxdz) {
        this.lxdz = lxdz == null ? null : lxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.bz
     *
     * @return the value of manufacturer.bz
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.bz
     *
     * @param bz the value for manufacturer.bz
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.lwje
     *
     * @return the value of manufacturer.lwje
     *
     * @mbggenerated
     */
    public String getLwje() {
        return lwje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.lwje
     *
     * @param lwje the value for manufacturer.lwje
     *
     * @mbggenerated
     */
    public void setLwje(String lwje) {
        this.lwje = lwje == null ? null : lwje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.mrghs
     *
     * @return the value of manufacturer.mrghs
     *
     * @mbggenerated
     */
    public String getMrghs() {
        return mrghs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.mrghs
     *
     * @param mrghs the value for manufacturer.mrghs
     *
     * @mbggenerated
     */
    public void setMrghs(String mrghs) {
        this.mrghs = mrghs == null ? null : mrghs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.pl
     *
     * @return the value of manufacturer.pl
     *
     * @mbggenerated
     */
    public String getPl() {
        return pl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.pl
     *
     * @param pl the value for manufacturer.pl
     *
     * @mbggenerated
     */
    public void setPl(String pl) {
        this.pl = pl == null ? null : pl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.lx
     *
     * @return the value of manufacturer.lx
     *
     * @mbggenerated
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.lx
     *
     * @param lx the value for manufacturer.lx
     *
     * @mbggenerated
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.dq
     *
     * @return the value of manufacturer.dq
     *
     * @mbggenerated
     */
    public String getDq() {
        return dq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.dq
     *
     * @param dq the value for manufacturer.dq
     *
     * @mbggenerated
     */
    public void setDq(String dq) {
        this.dq = dq == null ? null : dq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column manufacturer.jy
     *
     * @return the value of manufacturer.jy
     *
     * @mbggenerated
     */
    public String getJy() {
        return jy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column manufacturer.jy
     *
     * @param jy the value for manufacturer.jy
     *
     * @mbggenerated
     */
    public void setJy(String jy) {
        this.jy = jy == null ? null : jy.trim();
    }
}