package com.management_system.model;

import java.util.Date;

public class SalesOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.customer
     *
     * @mbggenerated
     */
    private Integer customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.ck
     *
     * @mbggenerated
     */
    private Integer ck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.date
     *
     * @mbggenerated
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.yfje
     *
     * @mbggenerated
     */
    private String yfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.sfje
     *
     * @mbggenerated
     */
    private String sfje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.agent
     *
     * @mbggenerated
     */
    private String agent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.bz
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.czy
     *
     * @mbggenerated
     */
    private String czy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.bid
     *
     * @mbggenerated
     */
    private String bid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.yhje
     *
     * @mbggenerated
     */
    private String yhje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.kh_gd
     *
     * @mbggenerated
     */
    private String khGd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.ishh
     *
     * @mbggenerated
     */
    private String ishh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.ispos
     *
     * @mbggenerated
     */
    private String ispos;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.xj
     *
     * @mbggenerated
     */
    private String xj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.yhk
     *
     * @mbggenerated
     */
    private String yhk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.djq
     *
     * @mbggenerated
     */
    private String djq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.fkje
     *
     * @mbggenerated
     */
    private String fkje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.zlje
     *
     * @mbggenerated
     */
    private String zlje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.wxid
     *
     * @mbggenerated
     */
    private String wxid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.dhflag
     *
     * @mbggenerated
     */
    private String dhflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.alipay
     *
     * @mbggenerated
     */
    private String alipay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.wx
     *
     * @mbggenerated
     */
    private String wx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.fkfs
     *
     * @mbggenerated
     */
    private String fkfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sales_order.PayNo
     *
     * @mbggenerated
     */
    private String payno;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.id
     *
     * @return the value of sales_order.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.id
     *
     * @param id the value for sales_order.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.customer
     *
     * @return the value of sales_order.customer
     *
     * @mbggenerated
     */
    public Integer getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.customer
     *
     * @param customer the value for sales_order.customer
     *
     * @mbggenerated
     */
    public void setCustomer(Integer customer) {
        this.customer = customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.ck
     *
     * @return the value of sales_order.ck
     *
     * @mbggenerated
     */
    public Integer getCk() {
        return ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.ck
     *
     * @param ck the value for sales_order.ck
     *
     * @mbggenerated
     */
    public void setCk(Integer ck) {
        this.ck = ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.date
     *
     * @return the value of sales_order.date
     *
     * @mbggenerated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.date
     *
     * @param date the value for sales_order.date
     *
     * @mbggenerated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.yfje
     *
     * @return the value of sales_order.yfje
     *
     * @mbggenerated
     */
    public String getYfje() {
        return yfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.yfje
     *
     * @param yfje the value for sales_order.yfje
     *
     * @mbggenerated
     */
    public void setYfje(String yfje) {
        this.yfje = yfje == null ? null : yfje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.sfje
     *
     * @return the value of sales_order.sfje
     *
     * @mbggenerated
     */
    public String getSfje() {
        return sfje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.sfje
     *
     * @param sfje the value for sales_order.sfje
     *
     * @mbggenerated
     */
    public void setSfje(String sfje) {
        this.sfje = sfje == null ? null : sfje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.agent
     *
     * @return the value of sales_order.agent
     *
     * @mbggenerated
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.agent
     *
     * @param agent the value for sales_order.agent
     *
     * @mbggenerated
     */
    public void setAgent(String agent) {
        this.agent = agent == null ? null : agent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.bz
     *
     * @return the value of sales_order.bz
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.bz
     *
     * @param bz the value for sales_order.bz
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.czy
     *
     * @return the value of sales_order.czy
     *
     * @mbggenerated
     */
    public String getCzy() {
        return czy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.czy
     *
     * @param czy the value for sales_order.czy
     *
     * @mbggenerated
     */
    public void setCzy(String czy) {
        this.czy = czy == null ? null : czy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.bid
     *
     * @return the value of sales_order.bid
     *
     * @mbggenerated
     */
    public String getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.bid
     *
     * @param bid the value for sales_order.bid
     *
     * @mbggenerated
     */
    public void setBid(String bid) {
        this.bid = bid == null ? null : bid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.yhje
     *
     * @return the value of sales_order.yhje
     *
     * @mbggenerated
     */
    public String getYhje() {
        return yhje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.yhje
     *
     * @param yhje the value for sales_order.yhje
     *
     * @mbggenerated
     */
    public void setYhje(String yhje) {
        this.yhje = yhje == null ? null : yhje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.kh_gd
     *
     * @return the value of sales_order.kh_gd
     *
     * @mbggenerated
     */
    public String getKhGd() {
        return khGd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.kh_gd
     *
     * @param khGd the value for sales_order.kh_gd
     *
     * @mbggenerated
     */
    public void setKhGd(String khGd) {
        this.khGd = khGd == null ? null : khGd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.ishh
     *
     * @return the value of sales_order.ishh
     *
     * @mbggenerated
     */
    public String getIshh() {
        return ishh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.ishh
     *
     * @param ishh the value for sales_order.ishh
     *
     * @mbggenerated
     */
    public void setIshh(String ishh) {
        this.ishh = ishh == null ? null : ishh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.ispos
     *
     * @return the value of sales_order.ispos
     *
     * @mbggenerated
     */
    public String getIspos() {
        return ispos;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.ispos
     *
     * @param ispos the value for sales_order.ispos
     *
     * @mbggenerated
     */
    public void setIspos(String ispos) {
        this.ispos = ispos == null ? null : ispos.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.xj
     *
     * @return the value of sales_order.xj
     *
     * @mbggenerated
     */
    public String getXj() {
        return xj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.xj
     *
     * @param xj the value for sales_order.xj
     *
     * @mbggenerated
     */
    public void setXj(String xj) {
        this.xj = xj == null ? null : xj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.yhk
     *
     * @return the value of sales_order.yhk
     *
     * @mbggenerated
     */
    public String getYhk() {
        return yhk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.yhk
     *
     * @param yhk the value for sales_order.yhk
     *
     * @mbggenerated
     */
    public void setYhk(String yhk) {
        this.yhk = yhk == null ? null : yhk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.djq
     *
     * @return the value of sales_order.djq
     *
     * @mbggenerated
     */
    public String getDjq() {
        return djq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.djq
     *
     * @param djq the value for sales_order.djq
     *
     * @mbggenerated
     */
    public void setDjq(String djq) {
        this.djq = djq == null ? null : djq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.fkje
     *
     * @return the value of sales_order.fkje
     *
     * @mbggenerated
     */
    public String getFkje() {
        return fkje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.fkje
     *
     * @param fkje the value for sales_order.fkje
     *
     * @mbggenerated
     */
    public void setFkje(String fkje) {
        this.fkje = fkje == null ? null : fkje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.zlje
     *
     * @return the value of sales_order.zlje
     *
     * @mbggenerated
     */
    public String getZlje() {
        return zlje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.zlje
     *
     * @param zlje the value for sales_order.zlje
     *
     * @mbggenerated
     */
    public void setZlje(String zlje) {
        this.zlje = zlje == null ? null : zlje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.wxid
     *
     * @return the value of sales_order.wxid
     *
     * @mbggenerated
     */
    public String getWxid() {
        return wxid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.wxid
     *
     * @param wxid the value for sales_order.wxid
     *
     * @mbggenerated
     */
    public void setWxid(String wxid) {
        this.wxid = wxid == null ? null : wxid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.dhflag
     *
     * @return the value of sales_order.dhflag
     *
     * @mbggenerated
     */
    public String getDhflag() {
        return dhflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.dhflag
     *
     * @param dhflag the value for sales_order.dhflag
     *
     * @mbggenerated
     */
    public void setDhflag(String dhflag) {
        this.dhflag = dhflag == null ? null : dhflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.alipay
     *
     * @return the value of sales_order.alipay
     *
     * @mbggenerated
     */
    public String getAlipay() {
        return alipay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.alipay
     *
     * @param alipay the value for sales_order.alipay
     *
     * @mbggenerated
     */
    public void setAlipay(String alipay) {
        this.alipay = alipay == null ? null : alipay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.wx
     *
     * @return the value of sales_order.wx
     *
     * @mbggenerated
     */
    public String getWx() {
        return wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.wx
     *
     * @param wx the value for sales_order.wx
     *
     * @mbggenerated
     */
    public void setWx(String wx) {
        this.wx = wx == null ? null : wx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.fkfs
     *
     * @return the value of sales_order.fkfs
     *
     * @mbggenerated
     */
    public String getFkfs() {
        return fkfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.fkfs
     *
     * @param fkfs the value for sales_order.fkfs
     *
     * @mbggenerated
     */
    public void setFkfs(String fkfs) {
        this.fkfs = fkfs == null ? null : fkfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sales_order.PayNo
     *
     * @return the value of sales_order.PayNo
     *
     * @mbggenerated
     */
    public String getPayno() {
        return payno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sales_order.PayNo
     *
     * @param payno the value for sales_order.PayNo
     *
     * @mbggenerated
     */
    public void setPayno(String payno) {
        this.payno = payno == null ? null : payno.trim();
    }
}