package com.management_system.model;

public class Warehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.goods_id
     *
     * @mbggenerated
     */
    private String goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.num
     *
     * @mbggenerated
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.cost_price
     *
     * @mbggenerated
     */
    private Integer costPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.ck
     *
     * @mbggenerated
     */
    private Integer ck;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.xssl
     *
     * @mbggenerated
     */
    private String xssl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.id
     *
     * @return the value of warehouse.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.id
     *
     * @param id the value for warehouse.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.goods_id
     *
     * @return the value of warehouse.goods_id
     *
     * @mbggenerated
     */
    public String getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.goods_id
     *
     * @param goodsId the value for warehouse.goods_id
     *
     * @mbggenerated
     */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId == null ? null : goodsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.num
     *
     * @return the value of warehouse.num
     *
     * @mbggenerated
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.num
     *
     * @param num the value for warehouse.num
     *
     * @mbggenerated
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.cost_price
     *
     * @return the value of warehouse.cost_price
     *
     * @mbggenerated
     */
    public Integer getCostPrice() {
        return costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.cost_price
     *
     * @param costPrice the value for warehouse.cost_price
     *
     * @mbggenerated
     */
    public void setCostPrice(Integer costPrice) {
        this.costPrice = costPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.ck
     *
     * @return the value of warehouse.ck
     *
     * @mbggenerated
     */
    public Integer getCk() {
        return ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.ck
     *
     * @param ck the value for warehouse.ck
     *
     * @mbggenerated
     */
    public void setCk(Integer ck) {
        this.ck = ck;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.xssl
     *
     * @return the value of warehouse.xssl
     *
     * @mbggenerated
     */
    public String getXssl() {
        return xssl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.xssl
     *
     * @param xssl the value for warehouse.xssl
     *
     * @mbggenerated
     */
    public void setXssl(String xssl) {
        this.xssl = xssl == null ? null : xssl.trim();
    }

    public Warehouse(Integer id, String goodsId, Integer num, Integer costPrice, Integer ck) {
        this.id = id;
        this.goodsId = goodsId;
        this.num = num;
        this.costPrice = costPrice;
        this.ck = ck;
    }

    public Warehouse() {
    }
}